name: ItemRarity
version: 0.2.1
main: cl.nightcore.itemrarity.ItemRarity
api-version: 1.20
softdepend: [ AuraSkills ]

commands:
  getscroll:
    description: Obtienes un pergamino de identificaci칩n.
    usage: /getscroll <cantidad>
  getmagic:
    description: Obtienes un objeto m치gico.
    usage: /getmagic <cantidad>
  getblessing:
    description: Obtienes un objeto bendici칩n.
    usage: /getblessing <cantidad>
  getredemption:
    description: Obtienes un objeto redenci칩n.
    usage: /getredemption <cantidad>
  getgem:
    description: Obtienes una gema.
  getremover:
    description: Obtienes un removedor de gemas.