name: ItemRarity
version: 1.0
main: cl.nightcore.itemrarity.ItemRarity
api-version: 1.20
softdepend: [AuraSkills,NBTAPI]

commands:
  getscroll:
    description: Obtienes un pergamino de identificaci칩n.
    usage: /getscroll <cantidad>
  getmagic:
    description: Obtienes un objeto m치gico.
    usage: /getmagic <cantidad>
  getblessing:
    description: Obtienes un objeto bendici칩n.
    usage: /getblessing <cantidad>
  getredemption:
    description: Obtienes un objeto redenci칩n.
    usage: /getredemption <cantidad>
  getcustomsword:
    description: Obten la espada.
    usage: /getredemption